/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rompecabezas;

import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import modelos.Puntaje;
import modelos.Tiempo;

/**
 *
 * @author usuario
 */
public class DialogoTableros extends javax.swing.JDialog {

    private String nombre;
    private Color color;
    private String imagen;
    private Tiempo tiempo;
    private Puntaje puntaje;
    private JLabel tTiempoLabel;

    public DialogoTableros(java.awt.Dialog parent, boolean modal, String nombre, Color color, String imagen, Font fuente) {
        super(parent, modal);
        initComponents();
        crearPanel(imagen);
        System.out.println(imagen);
        this.nombre = nombre;
        this.color = color;
        this.imagen = imagen;
        tTitulo.setText(nombre);
        jPanel2.setBackground(color);
        JLabel tTiempoLabel = new JLabel("0:00");
        jPanel2.add(tTiempoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 50, -1));
        tiempo = new Tiempo(tTiempoLabel);
        tiempo.iniciar();
        puntaje = new Puntaje(tiempo);
    }
    
    
    
    /**
     * Creates new form DialogoPixarGeneral
     */
    
    /*
    public DialogoTableros(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        crearPanel();
    }
    */
    
    public void crearPanel(String imagen){
        try {
            // this.panelRompe.setImagePath("src\\imagenesTableros\\IDisney\\DisneyT1.jpg");
            this.panelRompe.setImagePath(imagen);
        } catch (IOException ex) {
            Logger.getLogger(DialogoTableros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bContinuar = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();
        panelRompe = new presentacion.Tablero();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setForeground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tTitulo.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        tTitulo.setForeground(new java.awt.Color(0, 0, 0));
        tTitulo.setText("Titulo");
        jPanel2.add(tTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tiempo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Puntaje:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        bContinuar.setBackground(new java.awt.Color(102, 102, 255));
        bContinuar.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        bContinuar.setForeground(new java.awt.Color(0, 0, 0));
        bContinuar.setText("Continuar");
        bContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bContinuarActionPerformed(evt);
            }
        });
        jPanel2.add(bContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        bAtras.setBackground(new java.awt.Color(102, 102, 255));
        bAtras.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        bAtras.setForeground(new java.awt.Color(0, 0, 0));
        bAtras.setText("Atras");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });
        jPanel2.add(bAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        javax.swing.GroupLayout panelRompeLayout = new javax.swing.GroupLayout(panelRompe);
        panelRompe.setLayout(panelRompeLayout);
        panelRompeLayout.setHorizontalGroup(
            panelRompeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        panelRompeLayout.setVerticalGroup(
            panelRompeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jPanel2.add(panelRompe, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 480, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bAtrasActionPerformed

    private void bContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bContinuarActionPerformed
        // TODO add your handling code here:
        if(panelRompe.verificarGanador()){
            this.tiempo.pausar();
            DialogoFinal df = new DialogoFinal(null, true, tiempo);
            df.setVisible(true);
        }
    }//GEN-LAST:event_bContinuarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bContinuar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private presentacion.Tablero panelRompe;
    private javax.swing.JLabel tTitulo;
    // End of variables declaration//GEN-END:variables
}
