/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rompecabezas;

import java.awt.Color;

/**
 *
 * @author usuario
 */
public class VentanaRompeCabezas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRompeCabezas
     */
    public VentanaRompeCabezas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bDisney = new javax.swing.JButton();
        bPixar = new javax.swing.JButton();
        bMarvel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese la categoria en la que desea jugar");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 390, 30));

        bDisney.setBackground(new java.awt.Color(255, 102, 102));
        bDisney.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        bDisney.setForeground(new java.awt.Color(0, 0, 0));
        bDisney.setText("Disney");
        bDisney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDisneyActionPerformed(evt);
            }
        });
        jPanel2.add(bDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        bPixar.setBackground(new java.awt.Color(153, 255, 153));
        bPixar.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        bPixar.setForeground(new java.awt.Color(0, 0, 0));
        bPixar.setText("Pixar");
        bPixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPixarActionPerformed(evt);
            }
        });
        jPanel2.add(bPixar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        bMarvel.setBackground(new java.awt.Color(255, 153, 102));
        bMarvel.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        bMarvel.setForeground(new java.awt.Color(0, 0, 0));
        bMarvel.setText("Marvel");
        bMarvel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMarvelActionPerformed(evt);
            }
        });
        jPanel2.add(bMarvel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imgDisney (1).png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imgmarvel (1).jpg"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imgPixar (1).jpg"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 2, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Rompecabezas");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 390, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/r1.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bDisneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDisneyActionPerformed
        // TODO add your handling code here:
        DialogoDisney d1 = new DialogoDisney(this, true);
        d1.setVisible(true);
    }//GEN-LAST:event_bDisneyActionPerformed

    private void bMarvelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMarvelActionPerformed
        // TODO add your handling code here:
        DialogoMarvel d2 = new DialogoMarvel(this, true);
        d2.setVisible(true);
    }//GEN-LAST:event_bMarvelActionPerformed

    private void bPixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPixarActionPerformed
        // TODO add your handling code here:
        DialogoPixar d3 = new DialogoPixar(this, true);
        d3.setVisible(true);
    }//GEN-LAST:event_bPixarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        VentanaRompeCabezas p = new VentanaRompeCabezas();
        p.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDisney;
    private javax.swing.JButton bMarvel;
    private javax.swing.JButton bPixar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
